CREATE TABLE IF NOT EXISTS cpc_records (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  roc_year INT NOT NULL,
  month TINYINT NOT NULL,
  code VARCHAR(50) NOT NULL,
  license_plate VARCHAR(50) DEFAULT '',
  driver VARCHAR(100) DEFAULT '',
  trade_date VARCHAR(20) DEFAULT '',
  station VARCHAR(100) DEFAULT '',
  amount INT DEFAULT 0,
  note TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_cpc_period (roc_year, month)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
